import React from 'react'
import { storiesOf } from '@storybook/react'
import { Modal } from './Modal'
import ReadMe from './Modal.md'
import { usePopupTrigger } from '../../hooks'

storiesOf('Components', module)
  .addParameters({
    readme: {
      sidebar: ReadMe,
    },
  })
  .add('Modal', () => {
    const modal = usePopupTrigger()

    return (
      <main className="content">
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <button {...modal.trigger}>Click Me!</button>
        <Modal {...modal.popup}>
          <div>All the cool content that could ever be contented.</div>
        </Modal>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
        <p>Lorem ipsum paragraph...</p>
      </main>
    )
  })
